### PR TITLE
Test 02 19

### PR DESCRIPTION
**Pull request by Planetaeus**
Files have been created to facilitate test games.

### CODE REVIEW

**Comment by stassa** [comment]
Hello,

It was great to see your thorough and careful pull request. Thanks!

I'm in the final stretch of the work on a conference paper and I must
concentrate on it. I will have to leave your pull request aside for a moment.
I'll have some time to look at it carefully in the weekend. I'll also have to
remind myself how the game works- it's been a while.

Just a few thoughts from a quick look I had so far:

I'm concerned that some of your changes (e.g. in commit 22396db) are made
in-place to the text rulebook, under game/rulebook/txt/nests_and_insects.txt.
This file is automatically generated from the text in
game/rulebook/raw/rulebook.raw.txt and any changes you make to the former will
be overwritten when the rulebook-generation code is run. The way to make
changes to the game rules is to change the "raw" rulebook, under
game/rulebook/raw/rulebook.raw.txt. I guess it's confusing that the generated
rulebook is included in the repository but I figured it would make it easier
to read for folks who don't code.

Similar for the changes to character sheets. Changes to stats have to be
applied to the files under codes/data, where the character sheets take their
values from. Changes to formatting or rules reminders etc must be applied to
codez/src/charsheet.pl. Unfortunately that's one of the harder source files to
read and modify :/

Note however that any changes to rules text, including character sheets must
conform to the format of the generated rulebook which is, if I remember
correctly, 50 lines of text spanning 80 columns, with a monospaced font.
Otherwise the generated rulebook will look all wonky. You can test your
changes by running the program that generates the rulebook. Please ask me if
you don't know how to do this. I'll have to try and remind myself :)

I welcome any and all changes to the game rules and character and enemy stats
etc - I was just making them up as I went along anyway and with no playtesting
they are certainly not written in stone. With one exception: arithmetic is a
red line. The game is an exercise in making a tt-rpg without arithmetic (by
which I mean the four integer operations: +, -, / and *). If you would really
like to change this, may I suggest adding it as an optional alternative?

I'm ambivalent about character creation: picking up a character sheet and
playing without having to roll up a character is a conscious design choice.
Could you make character creation another optional rule? I was thinking a lot
of simpler computer games like Gauntlet at the time of writing the rules and I
wanted to simulate something like their simplicity of jumping straight into
the action without ceremony (like the ceremony of rolling up a character).

I was planning on including alternative rules in a rulebook section titled
"Plug-ins".

More soon, hopefully.
SP.

**Comment by stassa** [comment]
Just another quick note: Blindness is purposely designed to not do anything
mechanically, other than inform the Game Queen's descriptions of what the
characters perceive. The different values given to the stat for different
characters are also there for that reason: a character with 100% blindness
should not see anything, one with 80% blindness should see shadows etc. That
could certainly be clarified in the rules. It's also possible to add more
specific blindness mechanics, like abilities that create flashes of light to
temporarily or permanently blind characters who are not originally blind.

The idea is that being blind is a natural condition for many kinds of
arthropods so it shouldn't be treated in the same way as in a game where the
characters are humans for whom blindness is (considered to be?) a disability.
e.g. Ants may be blind but they are still extremely capable and deadly
opponents.

And of course relying on vision is a disadvantage in the depths of a dark Termite
nest, so some characters need to carry around light- spiders have their slaved
fireflies for that reason. But, yes, the rules need more clarity on all this.

**Comment by Planetaeus** [comment]
Thank you for your responses.

It was an accident that I made the pull request to the main repository,
that was intended to go to the main branch of my fork. I do not think what
I have done deserves to be reflected on the original work in its current
state.

The reason I am working directly with the text files is because it is at
present a more easily modifiable format than changing the code and the
input. I am not 100% confident on any of my changes, so for now I am
holding off on working with the rulebook generation files.

I have done my best to keep to the established red line of no arithmetic,
except with a few exceptions:

- I kept the Threat Rate, Survival Rate, and Initiative all dependent on
Attributes throughout the game to encourage investing in those attributes
with XP. The current form of leveling up does require some arithmetic. I
may solve this by using a standard XP value instead of a dice roll so that
the addition becomes easier. I also have Max Swarm, Max Wounds, and Damage
stat-dependent to give players a way to invest in those.

- In the Travel mechanic that I introduced, the level is added to the
number of connections being traversed. I'm not sure about this
implementation for other reasons.

As for character creation, I always intended for it to be an option
alongside the pre-generated characters. I know a lot of people who want to
make their own funky bugs, so I wanted to create an option for whatever
their heart desired.

Thank you for reaching out to me on this. I look forward to any insights
you have to offer on my work.

Kind regards,

Planetaeus

**Comment by stassa** [comment]
Hi Planetaeus and many apologies for the very long delay- I got so swamped
under work I didn't even get a weekend off until now.

I didn't realise your pull request was made by mistake. In that case you are
free to make any changes that you want and cross all my red lines. I think
that's covered in the license and in any case I would not think to demand that
you keep your fork in sync with my own priorities. Your fork, your game :)

Regarding the fate of this pull request. As far as I can tell everything is
under the new "notes" directory or in the games/rulebook/txt folder. I am
happy to keep your content in the notes file, although you'd have to move the
stuff from games/rulebook/txt to notes/ to avoif auto-erasure of some when the
rulebook is re-generated. Otherwise we just let this pull requst closed, I
guess.

I'm slowly reading through your notes in notes/proposed_changes.txt and
notes/rulebook_notes.txt.

**Pull request closed without merging**
